### ISSUE TITLE
AttributeError in Agent Chat System: 'PromptTokensDetails' object has no attribute 'get'

### ISSUE THREAD

**Issue by alexmanner** [AdieLaine/multi-agent-reasoning#2]
Description: When attempting to chat with agents (Agent 47 and Agent 74) in the Multi-Agent Reasoning Chatbot, the following error repeatedly occurs:

AttributeError: 'PromptTokensDetails' object has no attribute 'get'

The issue persists across multiple agents, and the system retries the request several times before eventually reaching the maximum retry limit. The error prevents generating a response from the agents.

Steps to Reproduce:

    Start the chatbot and select an agent (Agent 47 or Agent 74).
    Enter a message, such as "how are you."
    Observe the error in the logs, showing the AttributeError.

Expected Behavior: The agents should respond to the message as expected without encountering any errors.

Actual Behavior: The system encounters an AttributeError in the token handling process, and no response is generated from the agents.

Environment:

    macOS
    Multi-Agent Reasoning Chatbot
    Error occurs for both Agent 47 and Agent 74

**Comment by alexmanner** [comment]
The script `reasoning.py` was executed successfully, but it encountered an issue when attempting to chat with "Agent 47". The error indicates that there is an `AttributeError` related to the `PromptTokensDetails` object, which suggests there may be a bug in the script where it tries to access a non-existent `get` attribute. This caused repeated failed retries when communicating.

To resolve this, you may want to review the part of the code that handles interaction with agents, especially where `PromptTokensDetails` is used. Ensure the correct methods or attributes are available and used correctly. Debugging this code section or checking the documentation or source for `PromptTokensDetails` could also provide insights.

**Comment by alexmanner** [comment]
The error is indepent of the prompts I use.

"python reasoning.py
Successfully loaded agents configuration from 'agents.json'.
Available agents:
- Agent 47
- Agent 74
════════════════════════════════════════════════════════════════════════════════════════════════════
╔══════════════════════════════════════════════════════════╗
║              Multi-Agent Reasoning Chatbot               ║
╚══════════════════════════════════════════════════════════╝
Please select an option:
1. Chat with an agent
2. Use reasoning logic
3. Exit
Enter your choice (1/2/3): 1
Available agents to chat with:
1. Agent 47
2. Agent 74
Enter the number of the agent you want to chat with: 1
Starting chat with Agent 47. Type 'exit' to return to the main menu.
You: 1
Agent 47 agent-specific message token count: 877
2024-10-13 20:18:59,641 INFO:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2024-10-13 20:18:59,650 ERROR:Error in chat with agent 'Agent 47': AttributeError: 'PromptTokensDetails' object has no attribute 'get'
2024-10-13 20:18:59,650 INFO:Retrying chat in 1 seconds...
2024-10-13 20:19:01,653 INFO:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2024-10-13 20:19:01,656 ERROR:Error in chat with agent 'Agent 47': AttributeError: 'PromptTokensDetails' object has no attribute 'get'
2024-10-13 20:19:01,656 INFO:Retrying chat in 2 seconds...
2024-10-13 20:19:04,721 INFO:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2024-10-13 20:19:04,724 ERROR:Error in chat with agent 'Agent 47': AttributeError: 'PromptTokensDetails' object has no attribute 'get'
2024-10-13 20:19:04,724 ERROR:Agent 'Agent 47' reached maximum retry limit in chat.
Agent 47: An error occurred while generating a response.
You: exit
Exiting chat mode."""

**Comment by AdieLaine** [comment]
<img width="965" alt="Screenshot 2024-10-13 at 4 13 43 PM" src="https://github.com/user-attachments/assets/b6f153b4-2ba5-4606-bbd7-854db5ed1f5d">

Using both agents with a minimal greeting is not reproducing this error.

Please run in a fresh terminal, a prompt of: Hello how are you?

**Comment by AdieLaine** [comment]
Issue not reproducible when run using current code version. Please update local defined script imports. If error persist, reopen.
