### ISSUE TITLE
Incorrect swarm package installed via pip

### ISSUE THREAD

**Issue by alexmanner** [AdieLaine/multi-agent-reasoning#4]
Description: When installing the swarm package using the command pip install swarm, the package that gets installed is a space simulation game written in pygame. :-) 

The package in question can be found [here on PyPI](https://pypi.org/project/Swarm/), and its description states that it is a game developed in pygame.

To install the multi-agent orchestration swarm, it is

- pip install git+ssh://git@github.com/openai/swarm.git

- pip install git+https://github.com/openai/swarm.git

**Comment by AdieLaine** [comment]
modified pip install link to correct url options. refer to: [13142ee](https://github.com/AdieLaine/multi-agent-reasoning/commit/13142ee5187fe6eda895bc15c357ad6c9d78534f)
